# Generated by Django 5.0.6 on 2024-06-23 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us Page'},
        ),
        migrations.AddField(
            model_name='qhsecontent',
            name='content_ar',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AboutUsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_en', models.TextField(max_length=3000)),
                ('content_ar', models.TextField(max_length=3000)),
                ('related_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.about_us')),
            ],
            options={
                'verbose_name_plural': 'About Us Content',
            },
        ),
    ]
