# Generated by Django 5.0.6 on 2024-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0002_alter_about_us_options_qhsecontent_content_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuscontent',
            name='related_title',
        ),
        migrations.AlterField(
            model_name='qhsemaincontent',
            name='content_ar',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='qhsemaincontent',
            name='content_en',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.DeleteModel(
            name='About_Us',
        ),
        migrations.DeleteModel(
            name='AboutUsContent',
        ),
    ]
