# Generated by Django 5.0.6 on 2024-06-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0004_remove_qhsemaincontent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title_en', models.CharField(max_length=500)),
                ('content_en', models.TextField(max_length=5000)),
                ('title_ar', models.CharField(max_length=500)),
                ('content_ar', models.TextField(max_length=5000)),
                ('cover', models.ImageField(upload_to='CSR/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CSR',
            },
        ),
        migrations.CreateModel(
            name='CSRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CSR/%Y/%m/%d/')),
                ('related_CSR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pages.csr')),
            ],
            options={
                'verbose_name_plural': 'CSR Images',
            },
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
        migrations.RemoveField(
            model_name='qhsecontent',
            name='related_title',
        ),
        migrations.DeleteModel(
            name='QHSEImage',
        ),
        migrations.DeleteModel(
            name='QHSEPDF',
        ),
        migrations.DeleteModel(
            name='QHSEVideo',
        ),
        migrations.DeleteModel(
            name='QHSEContent',
        ),
        migrations.DeleteModel(
            name='QHSEMainContent',
        ),
    ]
