# Generated by Django 5.0.6 on 2024-07-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0006_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='managers/%Y/%m/%d/'),
        ),
    ]
