# Generated by Django 5.0.6 on 2024-06-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetroleumEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=100)),
                ('content_en', models.TextField(max_length=3000)),
                ('title_ar', models.CharField(max_length=100)),
                ('content_ar', models.TextField(max_length=3000)),
                ('image', models.FileField(upload_to='Operation Image/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Petroleum Engineering Activities',
            },
        ),
        migrations.AlterModelOptions(
            name='drilling',
            options={'verbose_name_plural': 'Drilling Activities'},
        ),
    ]
