# Generated by Django 5.0.6 on 2024-09-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_petroleumengineering_alter_drilling_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qhsecontent',
            options={'verbose_name_plural': 'HSE Content'},
        ),
        migrations.AlterModelOptions(
            name='qhseimage',
            options={'verbose_name_plural': 'HSE Images'},
        ),
        migrations.AlterModelOptions(
            name='qhsemaincontent',
            options={'verbose_name_plural': 'HSE Main Content'},
        ),
        migrations.AlterModelOptions(
            name='qhsepdf',
            options={'verbose_name_plural': 'HSE PDF'},
        ),
        migrations.AlterModelOptions(
            name='qhsevideo',
            options={'verbose_name_plural': 'HSE Videos'},
        ),
    ]
