# Generated by Django 5.0.6 on 2024-06-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csrimage',
            name='related_CSR',
        ),
        migrations.DeleteModel(
            name='CSR',
        ),
        migrations.DeleteModel(
            name='CSRImage',
        ),
    ]
